# CXX=clang++
CXX=g++

lab07Test: lab07Test.o WordCount.o tddFuncs.o
	${CXX} lab07Test.o WordCount.o tddFuncs.o -o lab07Test

# lab06Test.o: lab06Test.cpp
# 	${CXX} -c lab06Test.cpp

# WordCount.o: WordCount.cpp
# 	${CXX} -c WordCount.cpp


clean: 
	/bin/rm -f *.o lab07Test 